import type { Coordinate } from "@/types";
import { pointInPolygon, type Point } from "./validator";

/**
 * Shapefile-driven GIS boundary layers.
 *
 * Data: src/data/boundaries/*.json — generated by scripts/build-boundaries.mjs
 * from cahyadsn/wilayah_boundaries (MIT), actual administrative polygon
 * boundaries (MultiPolygon, EPSG:4326 [lon, lat]), NOT bounding boxes.
 * Source records only the coordinate; the matched admin hierarchy
 * (province -> city -> district) is resolved by spatial point-in-polygon.
 */

export interface BoundaryFeature {
  kode: string;
  nama: string;
  /** MultiPolygon: polygons -> rings -> [lon, lat] */
  polygons: Point[][][];
  /** [minLon, minLat, maxLon, maxLat] precomputed bbox for cheap pre-filter */
  bbox: [number, number, number, number];
}

export interface AdminMatchingCodes {
  provinceCode?: string;
  cityCode?: string;
  districtCode?: string;
}

export interface AdminMatchingResult {
  codes: AdminMatchingCodes;
  /** Resolved official names from shapefile for each level */
  names: { province?: string; city?: string; district?: string };
  /** Which levels could be resolved from real polygons */
  resolvedLevels: Array<"province" | "city" | "district">;
}

const RAW = {
  province: () => import("@/data/boundaries/provinsi.json"),
  city: () => import("@/data/boundaries/kabupaten.json"),
  district: () => import("@/data/boundaries/kecamatan.json"),
} as const;

interface FeatureCollection {
  type: string;
  features: Array<{
    type: string;
    properties: { kode: string; nama: string };
    geometry: { type: string; coordinates: number[][][][] };
  }>;
}

let cache:
  | {
      province: BoundaryFeature[];
      city: BoundaryFeature[];
      district: BoundaryFeature[];
      cityByProvince: Map<string, BoundaryFeature[]>;
      districtByCity: Map<string, BoundaryFeature[]>;
    }
  | undefined;

function toFeatures(raw: FeatureCollection): BoundaryFeature[] {
  return raw.features.map((f) => {
    const coords = f.geometry.coordinates;
    // coords: [polygon][ring][point] = [lon, lat]
    const polygons = coords.map((poly) =>
      poly.map((ring) => ring.map((pt) => [pt[0], pt[1]] as Point)),
    );
    let minLon = Infinity,
      minLat = Infinity,
      maxLon = -Infinity,
      maxLat = -Infinity;
    for (const poly of polygons) {
      for (const ring of poly) {
        for (const [lon, lat] of ring) {
          if (lon < minLon) minLon = lon;
          if (lat < minLat) minLat = lat;
          if (lon > maxLon) maxLon = lon;
          if (lat > maxLat) maxLat = lat;
        }
      }
    }
    return {
      kode: f.properties.kode,
      nama: f.properties.nama,
      polygons,
      bbox: [minLon, minLat, maxLon, maxLat],
    };
  });
}

async function loadBoundaries() {
  if (cache) return cache;

  const [provRaw, cityRaw, districtRaw] = await Promise.all([
    RAW.province(),
    RAW.city(),
    RAW.district(),
  ]);

  const province = toFeatures(provRaw as unknown as FeatureCollection);
  const city = toFeatures(cityRaw as unknown as FeatureCollection);
  const district = toFeatures(districtRaw as unknown as FeatureCollection);

  const cityByProvince = new Map<string, BoundaryFeature[]>();
  for (const c of city) {
    const provCode = c.kode.split(".")[0];
    const list = cityByProvince.get(provCode) || [];
    list.push(c);
    cityByProvince.set(provCode, list);
  }

  const districtByCity = new Map<string, BoundaryFeature[]>();
  for (const d of district) {
    const cityCode = d.kode.split(".").slice(0, 2).join(".");
    const list = districtByCity.get(cityCode) || [];
    list.push(d);
    districtByCity.set(cityCode, list);
  }

  cache = { province, city, district, cityByProvince, districtByCity };
  return cache;
}

function inBBox(f: BoundaryFeature, lon: number, lat: number): boolean {
  const [minLon, minLat, maxLon, maxLat] = f.bbox;
  return lon >= minLon && lon <= maxLon && lat >= minLat && lat <= maxLat;
}

function inFeature(f: BoundaryFeature, lon: number, lat: number): boolean {
  if (!inBBox(f, lon, lat)) return false;
  for (const poly of f.polygons) {
    // MultiPolygon: point inside if inside ANY polygon (holes handled by
    // even-odd rule across rings of that polygon via pointInPolygon).
    let current = false;
    for (const ring of poly) {
      if (pointInPolygon([lon, lat], ring)) current = !current;
    }
    if (current) return true;
  }
  return false;
}

/**
 * Resolve province/city/district codes & names from real shapefile polygons.
 * Walks the administrative hierarchy: province -> its cities -> its districts.
 */
export async function resolveAdminHierarchyAt(
  coord: Coordinate,
): Promise<AdminMatchingResult | null> {
  const { lat, lon } = coord;
  const b = await loadBoundaries();

  // Trim to candidates containing the lon/lat using per-feature bbox, then
  // run exact point-in-polygon against candidate polygons.
  const hit = (list: BoundaryFeature[]) =>
    list.filter((f) => inBBox(f, lon, lat));

  const provHits = hit(b.province).filter((f) => inFeature(f, lon, lat));
  if (provHits.length === 0) return null;
  const prov = provHits.sort(
    (a, z) => a.polygons.length - z.polygons.length,
  )[0];

  const provCode = prov.kode.split(".")[0];

  const cityHits = (b.cityByProvince.get(provCode) || []).filter((f) =>
    inFeature(f, lon, lat),
  );
  let city: BoundaryFeature | undefined;
  if (cityHits.length > 0) {
    city = cityHits.sort((a, z) => a.polygons.length - z.polygons.length)[0];
  }

  const districtHits = city
    ? (b.districtByCity.get(city.kode) || []).filter((f) =>
        inFeature(f, lon, lat),
      )
    : [];
  let district: BoundaryFeature | undefined;
  if (districtHits.length > 0) {
    district = districtHits.sort(
      (a, z) => a.polygons.length - z.polygons.length,
    )[0];
  }

  const resolvedLevels: AdminMatchingResult["resolvedLevels"] = ["province"];
  if (city) resolvedLevels.push("city");
  if (district) resolvedLevels.push("district");

  return {
    codes: {
      provinceCode: provCode,
      cityCode: city?.kode,
      districtCode: district?.kode,
    },
    names: {
      province: prov.nama,
      city: city?.nama,
      district: district?.nama,
    },
    resolvedLevels,
  };
}

/** Look up a boundary feature by its BPS administrative code. */
export async function findBoundaryByKode(
  level: "province" | "city" | "district",
  kode: string,
): Promise<BoundaryFeature | undefined> {
  const b = await loadBoundaries();
  const list = b[level];
  return list.find((f) => f.kode === kode);
}
